version: "3.9"

services:
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${ODOO_DB_USER}
      POSTGRES_PASSWORD: ${ODOO_DB_PASSWORD}
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    networks:
      - odoo-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    container_name: odoo16
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    user: "${HOST_UID}:${HOST_GID}"
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      ODOO_DB_USER: ${ODOO_DB_USER}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD}
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_addons:/mnt/extra-addons
      # Define named portainer volume or a host-based override with the ENV
      - ${ODOO_CONF_MOUNT}
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge

volumes:
  odoo_config:
  odoo_data:
  odoo_addons:
  odoo_db_data:
